steps:
  # Step 1: Build Tic Tac Toe Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/<gcpUser>/tictactoetest:latest'
      - '.'

  # Step 2: Push Tic Tac Toe Docker Image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/<gcpUser>/tictactoetest:latest'

# Logging options (optional, set Cloud Build logging mode)
options:
  logging: CLOUD_LOGGING_ONLY
